# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicNotices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticefile',
            name='notice_key',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='publicNotices.Notice'),
            preserve_default=False,
        ),
    ]
